from time import sleep
import os
from math import trunc, ceil, floor
print('\n\n')
print('#' * 40)
print('#    Calculadora Para Supermercado     #')
print('#        João Lucas Calc v1.1          #')
print('#                                      #')
print('#' * 40)
print('\n')
print('-=-' * 18)
print('『 Digite 1 Para Calcular o ％ entre dois Preços     』')
print('-=-' * 18)
print('\n')
print('-=-' * 18)
print('『 Digite 2 Para Cálculos de Promoção ％ Percentual  』')
print('-=-' * 18)
print('\n')
print('-=-' * 18)
print('『 Digite 3 Para Cálculos de Promoção Leve X Pague Y 』')
print('-=-' * 18)
print('\n')
print('-=-' * 25)
print('『 Digite 4 Para Fazer a Proporção do Preço de uma Embalagem Promocional 』')
print('-=-' * 25)
print('\n')
print('-=-' * 18)
print('『 Digite ( Ajuda ), para dúvidas Recomendado        』')
print('-=-' * 18)
print('\n')
user = str(input('➤  Digite a Opção Desejada e Tecle [Enter] : ')).upper().strip()
print('Carregando Aguarde ...')
#sleep(1)
print('\n')
os.system('clear')
if user == ('ajuda').upper().strip():
    print('-' * 28)
    print('『 Você Escolheu : [Ajuda] 』')
    print('-' * 28)
    print('❖ Para separação de casas decimais use Ponto [.] caso use Virgula [,] resultará em erros reinicie o programa clicando no botão [run again]\n\n❖ Para cada valor digitado Tecle [Enter] para abrir a próxima linha\n\n❖ Para rodar o algoritmo novamente clique no botão [run again] ou atualize a pagina ↷\n\n❖ Algoritmo em melhorias e aprendizado\n\n❖ Algoritmo desenvolvido por João Lucas Melo Souza ツ ')
if user == ('1').strip():
    print('-' * 55)
    print('『 Você Escolheu : [Calcular o ％ entre dois Preços] 』')
    print('-' * 55)
    print(' 』 Não use virgula --> separe por Ponto[.] 』')
    print('-' * 45)
    print('\n')
    preco1 = float(input('Digite o Primeiro Preço R$: '))
    print('=' * 35)
    preco2 = float(input('Digite o Segundo Preço R$: '))
    calc = (preco2 - preco1) / preco1 * 100
    print('=' * 35)
    print('\n')
    print('A Diferença em Percentual Real é de {:.2f}％, A Diferença Inteira é de {}％'.format(calc, trunc(calc)))
    print('=' * 76)
    dif_preco = preco2 - preco1
    print('A Diferença de Valores Entre os 2 Preços é de R$:{:.2f}'.format(dif_preco))
    print('=' * 54)
    print('\n\n')
    print('❖ Para rodar o algoritmo novamente clique no botão [run again] ou atualize a pagina ↷')
if user == ('2').strip():
    print('-' * 55)
    print('『 Você Escolheu : Cálculos de Promoção ％ Percentual 』')
    print('-' * 55)
    print(' 『 Não use virgula --> separe por Ponto[.] 』')
    print('-' * 45)
    print('\n')
    preco_partida = float(input('Digite o Preço de Partida do Produto R$: '))
    print('=' * 47)
    desconto = int(input('Digite o Desconto a Ser Aplicado na Segunda Unidade ％ : '))
    print('=' * 60)
    print('\n')
    preco_desc = preco_partida - (preco_partida * desconto / 100)
    preco_partida_desconto = preco_partida + preco_desc
    preco_un = (preco_partida + preco_desc) / 2
    print('=' * 31)
    print('Seu Preço de Partida é R$:{:.2f}'.format(preco_partida))
    print('=' * 31)
    print('Foi Aplicado o Desconto de {} ％, Na Segunda Unidade'.format(desconto))
    print('=' * 52)
    print('A Segunda Unidade Sairá Por R$:{:.2f}'.format(preco_desc))
    print('=' * 35)
    print('Comprando 2 Unidades Iguais Você Paga R$:{:.2f}'.format(preco_partida_desconto))
    print('=' * 46)
    print('Nesta Promoção a Unidade Sai a R$:{:.2f}'.format(preco_un))
    print('=' * 39)
    print('\n\n')
    print('❖ Para rodar o algoritmo novamente clique no botão [run again] ou atualize a pagina ↷')
if user == ('3').strip():
    print('-' * 57)
    print('『 Você Escolheu : Cálculos de Promoção Leve X Pague Y 』')
    print('-' * 57)
    print(' 『 Não use virgula --> separe por Ponto[.] 』')
    print('-' * 45)
    print('\n')
    preco_partida = float(input('Digite o Preço de Partida do Produto R$: '))
    print('=' * 46)
    leve_x = int(input('Leve: '))
    print('=' * 7)
    pague_y = int(input('Pague: '))
    print('=' * 8)
    print('\n')
    preco_partida_pague_y = preco_partida * pague_y
    preco_partida_leve_x = preco_partida_pague_y / leve_x
    print('=' * 31)
    print('Seu Preço de Partida é R$:{:.2f}'.format(preco_partida))
    print('=' * 31)
    print('Leve: {} Pague: {}'.format(leve_x, pague_y))
    print('=' * 16)
    print('Nesta Promoção a Unidade Sai a R$:{:.2f}'.format(preco_partida_leve_x))
    print('=' * 38)
    print('\n\n')
    print('❖ Para rodar o algoritmo novamente clique no botão [run again] ou atualize a pagina ↷')
if user == ('4').strip():
      print('-' * 86)
      print('Você Escolheu : 『 Fazer a Proporção do Preço de um Produto de Embalagem Promocional 』')
      print('-' * 86)
      print(' 『 Não use virgula --> separe por Ponto[.] 』')
      print('-' * 45)
      print('\n')
      print('=' * 45)
      preco_partida = float(input('Digite o Preço de Partida do Produto R$: '))
      print('=' * 45)
      grama = float(input('Digite o Peso Original do Produto: '))
      print('=' * 38)
      grama_prom = float(input('Digite o Peso Promocional do Produto: '))
      print('=' * 43)
      calc_origin = preco_partida / grama
      calc_prom = calc_origin * grama_prom
      print('\n\n')
      print('Seu Preço de Partida é R$:{:.2f}'.format(preco_partida))
      print('=' * 30)
      print('Preço Final Consumidor da Embalagem Promocional é R$:{:.2f} '.format(calc_prom))
      print('=' * 57)
      print('\n\n')
      print('❖ Para rodar o algoritmo novamente clique no botão [run again] ou atualize a pagina ↷')









